export enum Permission {
  OBTENER_UFVS_DEL_BCB = 'OBTENER_UFVS_DEL_BCB_ACT',
  OBTENER_UFVS = 'OBTENER_UFVS_ACT',

  BITACORAS = 'VISUALIZAR_BITACORAS_ACT',

  CREAR_ACTIVO = 'CREAR_ACTIVO_ACT',
  OBTENER_ACTIVOS = 'OBTENER_ACTIVOS_ACT',
  EDITAR_ACTIVO = 'EDITAR_ACTIVO_ACT',
  ELIMINAR_ACTIVO = 'ELIMINAR_ACTIVO_ACT',
  
  OBTENER_USUARIOS = 'OBTENER_USUARIOS',      

  CREAR_GRUPO_CONTABLE = 'CREAR_GRUPO_CONTABLE_ACT',
  OBTENER_GRUPOS_CONTABLES = 'OBTENER_GRUPOS_CONTABLES_ACT',
  EDITAR_GRUPO_CONTABLE = 'EDITAR_GRUPO_CONTABLE_ACT',
  ELIMINAR_GRUPO_CONTABLE = 'ELIMINAR_GRUPO_CONTABLE_ACT',
  
  CREAR_PROVEEDOR = 'CREAR_PROVEEDOR_ACT',
  OBTENER_PROVEEDORES = 'OBTENER_PROVEEDORES_ACT',
  EDITAR_PROVEEDOR = 'EDITAR_PROVEEDOR_ACT',
  ELIMINAR_PROVEEDOR = 'ELIMINAR_PROVEEDOR_ACT',
  REESTABLECER_PROVEEDOR = 'REESTABLECER_PROVEEDOR_ACT',

  CREAR_PERMISO = 'CREAR_PERMISO_ACT',
  OBTENER_PERMISOS = 'OBTENER_PERMISOS_ACT',
  EDITAR_PERMISO = 'EDITAR_PERMISO_ACT',
  ELIMINAR_PERMISO = 'ELIMINAR_PERMISO_ACT' ,
}

