# fly.toml app configuration file generated for twilight-dust-6919 on 2023-07-19T23:19:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twilight-dust-6919"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
